### ISSUE TITLE
Texture license?

### ISSUE THREAD

**Issue by lnjX** [ExterminatorJeff/UndergroundBiomes#17]
I want to use some of the textures in a mod/game for Minetest. Under which license can I use them?
Creative Commons? The recommended texture license for Minetest projects is CC BY-SA 3.0/4.0.

With this license I would have to write that the textures are by you and that they are under the CC BY-SA 3.0/4.0, so nobody is allowed to change the license, if he changes something about the texture.

Here is my project repo.: https://github.com/Gamerbude/Minetest_TNG
And here would you stand: https://github.com/Gamerbude/Minetest_TNG/blob/master/mods/default/README.txt

And here is a short and understandable declaration of the suggested license: https://creativecommons.org/licenses/by-sa/4.0/

**Comment by Zeno410** [comment]
The textures are not mine. The textures are the work of theOrder, see the post on this page. http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287082-1-6-x-1-5-x-1-4-7-underground-biomes-forge-smp?page=38#entry24041892

I got permission to include them in UB a while back.

**Comment by lnjX** [comment]
Okay
