### ISSUE TITLE
"Stone Name" Cobble Wall and "Stone Name" Cobblestone Stairs not craftable

### ISSUE THREAD

**Issue by UncleSam139** [ExterminatorJeff/UndergroundBiomes#18]
Every time when you want to craft another wall then the cobblestone wall, you only can craft the Cobblestone Wall. Same goes for the Cobblestone Stairs.

For example, 6x Migmatite Cobblestone gives Cobblestone Wall, not Migmatite Cobble Wall.

**Comment by grompe** [comment]
Probably you meant to open an issue on a page of maintained version of this mod.

**Comment by UncleSam139** [comment]
Sorry, wrong version. My mistake.
