### ISSUE TITLE
Hardness reads current stone hardness

### ISSUE THREAD

**Issue by iguanaman** [ExterminatorJeff/UndergroundBiomes#9]
I make a mod that modifies the hardness of smooth stone and I'd like to include support for Underground Biomes.

Since your blocks don't support setHardness (as it returns the value directly in getBlockHardness) I'd have to replace all classes with extended ones of my own.

Would you consider changing the getBlockHardness function to read the current hardness of stone and then multiply it by the modifier, rather than use the default Minecraft value of 1.5f?

Thanks

**Comment by grompe** [comment]
Use:

```
exterminatorJeff.undergroundBiomes.common.UndergroundBiomes.hardnessModifier = your_value;
exterminatorJeff.undergroundBiomes.common.UndergroundBiomes.resistanceModifier = your_value;
```

**Comment by iguanaman** [comment]
Much appreciated :+1:
